import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import HeaderLayout from "@/components/HeaderLayout";
import { CartProvider } from "@/contexts/cartContext/CartProvider";
import { SearchProvider } from '../contexts/searchContext/SearchProvider'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VINI STORE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <SearchProvider>
            <HeaderLayout />
            {children}
          </SearchProvider>
        </CartProvider>
      </body>
    </html >
  );
}
